### ISSUE TITLE
PixiJS V4:  Cannot read property 'plugins' of undefined pixi.nativeLineGL.js:63

### ISSUE THREAD

**Issue by m-ahmadi** [DavidBM/pixi-nativeGLline#2]
<script type="text/javascript" src="pixi-v4.js"></script>
<br>
<script type="text/javascript" src="pixi.nativeLineGL.js"></script>

Cannot read property 'plugins' of undefined pixi.nativeLineGL.js:63

**Comment by DavidBM** [comment]
Hi! Thanks for the issue. 

Now it should work :)

I added and example for better understanding of how works.

I close the issue, if you have any problem related with the original, tell me and I will reopen.

**Comment by DavidBM** [comment]
This morning I realize that the patch is not working. The new ES6 code of Pixi makes difficult to patch the library from the exterior. I'm afraid that I can't solve the problem right now. I will try con do it in the future. But doesn't seems that have easy fix. :(

**Comment by DavidBM** [comment]
Hey!

I made this pull request for pixijs

If you like to have this feature in the official pixijs, support it! 

https://github.com/pixijs/pixi.js/pull/3328
